# Peter's Config file for CircleCI
# cimg/python didnt work
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/password_check
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv password_check
            . password_check/bin/activate &&
            pip install -r requirements.txt
      - run: 
           name: run tests
           command:
              . password_check/bin/activate &&
              python -m pytest tests/ -v --cov
workflows:
  version: 2
  build:
    jobs:
      - build 
      